scrape_configs:
  - job_name: 'product'
    metrics_path: '/actuator/prometheus'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:8086'] # Use host.docker.internal for Windows/Mac

  - job_name: 'redis'
    metrics_path: '/metrics'
    scrape_interval: 2s
    static_configs:
      - targets: ['host.docker.internal:9121']
